// Generated by gencpp from file robotiq_2f_gripper_msgs/CommandRobotiqGripperAction.msg
// DO NOT EDIT!


#ifndef ROBOTIQ_2F_GRIPPER_MSGS_MESSAGE_COMMANDROBOTIQGRIPPERACTION_H
#define ROBOTIQ_2F_GRIPPER_MSGS_MESSAGE_COMMANDROBOTIQGRIPPERACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robotiq_2f_gripper_msgs/CommandRobotiqGripperActionGoal.h>
#include <robotiq_2f_gripper_msgs/CommandRobotiqGripperActionResult.h>
#include <robotiq_2f_gripper_msgs/CommandRobotiqGripperActionFeedback.h>

namespace robotiq_2f_gripper_msgs
{
template <class ContainerAllocator>
struct CommandRobotiqGripperAction_
{
  typedef CommandRobotiqGripperAction_<ContainerAllocator> Type;

  CommandRobotiqGripperAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  CommandRobotiqGripperAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction_<ContainerAllocator> const> ConstPtr;

}; // struct CommandRobotiqGripperAction_

typedef ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction_<std::allocator<void> > CommandRobotiqGripperAction;

typedef boost::shared_ptr< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction > CommandRobotiqGripperActionPtr;
typedef boost::shared_ptr< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction const> CommandRobotiqGripperActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction_<ContainerAllocator1> & lhs, const ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction_<ContainerAllocator1> & lhs, const ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotiq_2f_gripper_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "032bc3d9e57d9371c7d34e6cda2e7867";
  }

  static const char* value(const ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x032bc3d9e57d9371ULL;
  static const uint64_t static_value2 = 0xc7d34e6cda2e7867ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotiq_2f_gripper_msgs/CommandRobotiqGripperAction";
  }

  static const char* value(const ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"CommandRobotiqGripperActionGoal action_goal\n"
"CommandRobotiqGripperActionResult action_result\n"
"CommandRobotiqGripperActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: robotiq_2f_gripper_msgs/CommandRobotiqGripperActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"CommandRobotiqGripperGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: robotiq_2f_gripper_msgs/CommandRobotiqGripperGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# See Robotiq documentation for fields documentation.\n"
"# See Robotiq documentation for fields documentation.\n"
"\n"
"#goal definition\n"
"bool emergency_release\n"
"uint32 emergency_release_dir\n"
"bool stop\n"
"float32 position #[m] Distance in bewteen fingers \n"
"float32 speed    #[m/s] Speed (Min: 0.013m/s - Max: 0.1m/s)\n"
"float32 force    #[%] Percentage of gripper force to apply (Min: 0.0% - Max: 100.0%)\n"
"\n"
"================================================================================\n"
"MSG: robotiq_2f_gripper_msgs/CommandRobotiqGripperActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"CommandRobotiqGripperResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: robotiq_2f_gripper_msgs/CommandRobotiqGripperResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"Header header\n"
"bool is_ready\n"
"bool is_reset\n"
"bool is_moving\n"
"bool obj_detected\n"
"uint8 fault_status\n"
"float32 position\n"
"float32 requested_position\n"
"float32 current\n"
"\n"
"================================================================================\n"
"MSG: robotiq_2f_gripper_msgs/CommandRobotiqGripperActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"CommandRobotiqGripperFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: robotiq_2f_gripper_msgs/CommandRobotiqGripperFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"Header header\n"
"bool is_ready\n"
"bool is_reset\n"
"bool is_moving\n"
"bool obj_detected\n"
"uint8 fault_status\n"
"float32 position\n"
"float32 requested_position\n"
"float32 current\n"
"\n"
;
  }

  static const char* value(const ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommandRobotiqGripperAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotiq_2f_gripper_msgs::CommandRobotiqGripperAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTIQ_2F_GRIPPER_MSGS_MESSAGE_COMMANDROBOTIQGRIPPERACTION_H
