// Generated by gencpp from file robotiq_2f_gripper_msgs/CommandRobotiqGripperActionGoal.msg
// DO NOT EDIT!


#ifndef ROBOTIQ_2F_GRIPPER_MSGS_MESSAGE_COMMANDROBOTIQGRIPPERACTIONGOAL_H
#define ROBOTIQ_2F_GRIPPER_MSGS_MESSAGE_COMMANDROBOTIQGRIPPERACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <robotiq_2f_gripper_msgs/CommandRobotiqGripperGoal.h>

namespace robotiq_2f_gripper_msgs
{
template <class ContainerAllocator>
struct CommandRobotiqGripperActionGoal_
{
  typedef CommandRobotiqGripperActionGoal_<ContainerAllocator> Type;

  CommandRobotiqGripperActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  CommandRobotiqGripperActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::robotiq_2f_gripper_msgs::CommandRobotiqGripperGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CommandRobotiqGripperActionGoal_

typedef ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<std::allocator<void> > CommandRobotiqGripperActionGoal;

typedef boost::shared_ptr< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal > CommandRobotiqGripperActionGoalPtr;
typedef boost::shared_ptr< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal const> CommandRobotiqGripperActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator1> & lhs, const ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator1> & lhs, const ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotiq_2f_gripper_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f0063c16461ada508b5134444e0915f7";
  }

  static const char* value(const ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf0063c16461ada50ULL;
  static const uint64_t static_value2 = 0x8b5134444e0915f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotiq_2f_gripper_msgs/CommandRobotiqGripperActionGoal";
  }

  static const char* value(const ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"CommandRobotiqGripperGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: robotiq_2f_gripper_msgs/CommandRobotiqGripperGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# See Robotiq documentation for fields documentation.\n"
"# See Robotiq documentation for fields documentation.\n"
"\n"
"#goal definition\n"
"bool emergency_release\n"
"uint32 emergency_release_dir\n"
"bool stop\n"
"float32 position #[m] Distance in bewteen fingers \n"
"float32 speed    #[m/s] Speed (Min: 0.013m/s - Max: 0.1m/s)\n"
"float32 force    #[%] Percentage of gripper force to apply (Min: 0.0% - Max: 100.0%)\n"
;
  }

  static const char* value(const ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommandRobotiqGripperActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotiq_2f_gripper_msgs::CommandRobotiqGripperActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::robotiq_2f_gripper_msgs::CommandRobotiqGripperGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTIQ_2F_GRIPPER_MSGS_MESSAGE_COMMANDROBOTIQGRIPPERACTIONGOAL_H
