// Auto-generated. Do not edit!

// (in-package robotiq_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CModelCommandFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.position = null;
      this.activated = null;
      this.stalled = null;
      this.reached_goal = null;
    }
    else {
      if (initObj.hasOwnProperty('position')) {
        this.position = initObj.position
      }
      else {
        this.position = 0.0;
      }
      if (initObj.hasOwnProperty('activated')) {
        this.activated = initObj.activated
      }
      else {
        this.activated = false;
      }
      if (initObj.hasOwnProperty('stalled')) {
        this.stalled = initObj.stalled
      }
      else {
        this.stalled = false;
      }
      if (initObj.hasOwnProperty('reached_goal')) {
        this.reached_goal = initObj.reached_goal
      }
      else {
        this.reached_goal = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CModelCommandFeedback
    // Serialize message field [position]
    bufferOffset = _serializer.float64(obj.position, buffer, bufferOffset);
    // Serialize message field [activated]
    bufferOffset = _serializer.bool(obj.activated, buffer, bufferOffset);
    // Serialize message field [stalled]
    bufferOffset = _serializer.bool(obj.stalled, buffer, bufferOffset);
    // Serialize message field [reached_goal]
    bufferOffset = _serializer.bool(obj.reached_goal, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CModelCommandFeedback
    let len;
    let data = new CModelCommandFeedback(null);
    // Deserialize message field [position]
    data.position = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [activated]
    data.activated = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [stalled]
    data.stalled = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [reached_goal]
    data.reached_goal = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 11;
  }

  static datatype() {
    // Returns string type for a message object
    return 'robotiq_msgs/CModelCommandFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '0c22872a7859572c1fc9fe8ee6018789';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Feedback
    float64     position
    bool        activated
    bool        stalled
    bool        reached_goal
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CModelCommandFeedback(null);
    if (msg.position !== undefined) {
      resolved.position = msg.position;
    }
    else {
      resolved.position = 0.0
    }

    if (msg.activated !== undefined) {
      resolved.activated = msg.activated;
    }
    else {
      resolved.activated = false
    }

    if (msg.stalled !== undefined) {
      resolved.stalled = msg.stalled;
    }
    else {
      resolved.stalled = false
    }

    if (msg.reached_goal !== undefined) {
      resolved.reached_goal = msg.reached_goal;
    }
    else {
      resolved.reached_goal = false
    }

    return resolved;
    }
};

module.exports = CModelCommandFeedback;
