# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robotiq_2f_gripper_msgs/CommandRobotiqGripperAction.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import actionlib_msgs.msg
import genpy
import robotiq_2f_gripper_msgs.msg
import std_msgs.msg

class CommandRobotiqGripperAction(genpy.Message):
  _md5sum = "032bc3d9e57d9371c7d34e6cda2e7867"
  _type = "robotiq_2f_gripper_msgs/CommandRobotiqGripperAction"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

CommandRobotiqGripperActionGoal action_goal
CommandRobotiqGripperActionResult action_result
CommandRobotiqGripperActionFeedback action_feedback

================================================================================
MSG: robotiq_2f_gripper_msgs/CommandRobotiqGripperActionGoal
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
CommandRobotiqGripperGoal goal

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: actionlib_msgs/GoalID
# The stamp should store the time at which this goal was requested.
# It is used by an action server when it tries to preempt all
# goals that were requested before a certain time
time stamp

# The id provides a way to associate feedback and
# result message with specific goal requests. The id
# specified must be unique.
string id


================================================================================
MSG: robotiq_2f_gripper_msgs/CommandRobotiqGripperGoal
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# See Robotiq documentation for fields documentation.
# See Robotiq documentation for fields documentation.

#goal definition
bool emergency_release
uint32 emergency_release_dir
bool stop
float32 position #[m] Distance in bewteen fingers 
float32 speed    #[m/s] Speed (Min: 0.013m/s - Max: 0.1m/s)
float32 force    #[%] Percentage of gripper force to apply (Min: 0.0% - Max: 100.0%)

================================================================================
MSG: robotiq_2f_gripper_msgs/CommandRobotiqGripperActionResult
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
CommandRobotiqGripperResult result

================================================================================
MSG: actionlib_msgs/GoalStatus
GoalID goal_id
uint8 status
uint8 PENDING         = 0   # The goal has yet to be processed by the action server
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                            #   and has since completed its execution (Terminal State)
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                            #    to some failure (Terminal State)
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                            #    because the goal was unattainable or invalid (Terminal State)
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                            #    and has not yet completed execution
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                            #    but the action server has not yet confirmed that the goal is canceled
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                            #    and was successfully cancelled (Terminal State)
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                            #    sent over the wire by an action server

#Allow for the user to associate a string with GoalStatus for debugging
string text


================================================================================
MSG: robotiq_2f_gripper_msgs/CommandRobotiqGripperResult
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#result definition
Header header
bool is_ready
bool is_reset
bool is_moving
bool obj_detected
uint8 fault_status
float32 position
float32 requested_position
float32 current

================================================================================
MSG: robotiq_2f_gripper_msgs/CommandRobotiqGripperActionFeedback
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
CommandRobotiqGripperFeedback feedback

================================================================================
MSG: robotiq_2f_gripper_msgs/CommandRobotiqGripperFeedback
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#feedback
Header header
bool is_ready
bool is_reset
bool is_moving
bool obj_detected
uint8 fault_status
float32 position
float32 requested_position
float32 current

"""
  __slots__ = ['action_goal','action_result','action_feedback']
  _slot_types = ['robotiq_2f_gripper_msgs/CommandRobotiqGripperActionGoal','robotiq_2f_gripper_msgs/CommandRobotiqGripperActionResult','robotiq_2f_gripper_msgs/CommandRobotiqGripperActionFeedback']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       action_goal,action_result,action_feedback

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CommandRobotiqGripperAction, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.action_goal is None:
        self.action_goal = robotiq_2f_gripper_msgs.msg.CommandRobotiqGripperActionGoal()
      if self.action_result is None:
        self.action_result = robotiq_2f_gripper_msgs.msg.CommandRobotiqGripperActionResult()
      if self.action_feedback is None:
        self.action_feedback = robotiq_2f_gripper_msgs.msg.CommandRobotiqGripperActionFeedback()
    else:
      self.action_goal = robotiq_2f_gripper_msgs.msg.CommandRobotiqGripperActionGoal()
      self.action_result = robotiq_2f_gripper_msgs.msg.CommandRobotiqGripperActionResult()
      self.action_feedback = robotiq_2f_gripper_msgs.msg.CommandRobotiqGripperActionFeedback()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.action_goal.header.seq, _x.action_goal.header.stamp.secs, _x.action_goal.header.stamp.nsecs))
      _x = self.action_goal.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.action_goal.goal_id.stamp.secs, _x.action_goal.goal_id.stamp.nsecs))
      _x = self.action_goal.goal_id.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BIB3f3I().pack(_x.action_goal.goal.emergency_release, _x.action_goal.goal.emergency_release_dir, _x.action_goal.goal.stop, _x.action_goal.goal.position, _x.action_goal.goal.speed, _x.action_goal.goal.force, _x.action_result.header.seq, _x.action_result.header.stamp.secs, _x.action_result.header.stamp.nsecs))
      _x = self.action_result.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.action_result.status.goal_id.stamp.secs, _x.action_result.status.goal_id.stamp.nsecs))
      _x = self.action_result.status.goal_id.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.action_result.status.status
      buff.write(_get_struct_B().pack(_x))
      _x = self.action_result.status.text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.action_result.result.header.seq, _x.action_result.result.header.stamp.secs, _x.action_result.result.header.stamp.nsecs))
      _x = self.action_result.result.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_5B3f3I().pack(_x.action_result.result.is_ready, _x.action_result.result.is_reset, _x.action_result.result.is_moving, _x.action_result.result.obj_detected, _x.action_result.result.fault_status, _x.action_result.result.position, _x.action_result.result.requested_position, _x.action_result.result.current, _x.action_feedback.header.seq, _x.action_feedback.header.stamp.secs, _x.action_feedback.header.stamp.nsecs))
      _x = self.action_feedback.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.action_feedback.status.goal_id.stamp.secs, _x.action_feedback.status.goal_id.stamp.nsecs))
      _x = self.action_feedback.status.goal_id.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.action_feedback.status.status
      buff.write(_get_struct_B().pack(_x))
      _x = self.action_feedback.status.text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.action_feedback.feedback.header.seq, _x.action_feedback.feedback.header.stamp.secs, _x.action_feedback.feedback.header.stamp.nsecs))
      _x = self.action_feedback.feedback.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_5B3f().pack(_x.action_feedback.feedback.is_ready, _x.action_feedback.feedback.is_reset, _x.action_feedback.feedback.is_moving, _x.action_feedback.feedback.obj_detected, _x.action_feedback.feedback.fault_status, _x.action_feedback.feedback.position, _x.action_feedback.feedback.requested_position, _x.action_feedback.feedback.current))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.action_goal is None:
        self.action_goal = robotiq_2f_gripper_msgs.msg.CommandRobotiqGripperActionGoal()
      if self.action_result is None:
        self.action_result = robotiq_2f_gripper_msgs.msg.CommandRobotiqGripperActionResult()
      if self.action_feedback is None:
        self.action_feedback = robotiq_2f_gripper_msgs.msg.CommandRobotiqGripperActionFeedback()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.action_goal.header.seq, _x.action_goal.header.stamp.secs, _x.action_goal.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_goal.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_goal.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.action_goal.goal_id.stamp.secs, _x.action_goal.goal_id.stamp.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_goal.goal_id.id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_goal.goal_id.id = str[start:end]
      _x = self
      start = end
      end += 30
      (_x.action_goal.goal.emergency_release, _x.action_goal.goal.emergency_release_dir, _x.action_goal.goal.stop, _x.action_goal.goal.position, _x.action_goal.goal.speed, _x.action_goal.goal.force, _x.action_result.header.seq, _x.action_result.header.stamp.secs, _x.action_result.header.stamp.nsecs,) = _get_struct_BIB3f3I().unpack(str[start:end])
      self.action_goal.goal.emergency_release = bool(self.action_goal.goal.emergency_release)
      self.action_goal.goal.stop = bool(self.action_goal.goal.stop)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_result.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_result.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.action_result.status.goal_id.stamp.secs, _x.action_result.status.goal_id.stamp.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_result.status.goal_id.id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_result.status.goal_id.id = str[start:end]
      start = end
      end += 1
      (self.action_result.status.status,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_result.status.text = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_result.status.text = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.action_result.result.header.seq, _x.action_result.result.header.stamp.secs, _x.action_result.result.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_result.result.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_result.result.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 29
      (_x.action_result.result.is_ready, _x.action_result.result.is_reset, _x.action_result.result.is_moving, _x.action_result.result.obj_detected, _x.action_result.result.fault_status, _x.action_result.result.position, _x.action_result.result.requested_position, _x.action_result.result.current, _x.action_feedback.header.seq, _x.action_feedback.header.stamp.secs, _x.action_feedback.header.stamp.nsecs,) = _get_struct_5B3f3I().unpack(str[start:end])
      self.action_result.result.is_ready = bool(self.action_result.result.is_ready)
      self.action_result.result.is_reset = bool(self.action_result.result.is_reset)
      self.action_result.result.is_moving = bool(self.action_result.result.is_moving)
      self.action_result.result.obj_detected = bool(self.action_result.result.obj_detected)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_feedback.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_feedback.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.action_feedback.status.goal_id.stamp.secs, _x.action_feedback.status.goal_id.stamp.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_feedback.status.goal_id.id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_feedback.status.goal_id.id = str[start:end]
      start = end
      end += 1
      (self.action_feedback.status.status,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_feedback.status.text = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_feedback.status.text = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.action_feedback.feedback.header.seq, _x.action_feedback.feedback.header.stamp.secs, _x.action_feedback.feedback.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_feedback.feedback.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_feedback.feedback.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 17
      (_x.action_feedback.feedback.is_ready, _x.action_feedback.feedback.is_reset, _x.action_feedback.feedback.is_moving, _x.action_feedback.feedback.obj_detected, _x.action_feedback.feedback.fault_status, _x.action_feedback.feedback.position, _x.action_feedback.feedback.requested_position, _x.action_feedback.feedback.current,) = _get_struct_5B3f().unpack(str[start:end])
      self.action_feedback.feedback.is_ready = bool(self.action_feedback.feedback.is_ready)
      self.action_feedback.feedback.is_reset = bool(self.action_feedback.feedback.is_reset)
      self.action_feedback.feedback.is_moving = bool(self.action_feedback.feedback.is_moving)
      self.action_feedback.feedback.obj_detected = bool(self.action_feedback.feedback.obj_detected)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.action_goal.header.seq, _x.action_goal.header.stamp.secs, _x.action_goal.header.stamp.nsecs))
      _x = self.action_goal.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.action_goal.goal_id.stamp.secs, _x.action_goal.goal_id.stamp.nsecs))
      _x = self.action_goal.goal_id.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BIB3f3I().pack(_x.action_goal.goal.emergency_release, _x.action_goal.goal.emergency_release_dir, _x.action_goal.goal.stop, _x.action_goal.goal.position, _x.action_goal.goal.speed, _x.action_goal.goal.force, _x.action_result.header.seq, _x.action_result.header.stamp.secs, _x.action_result.header.stamp.nsecs))
      _x = self.action_result.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.action_result.status.goal_id.stamp.secs, _x.action_result.status.goal_id.stamp.nsecs))
      _x = self.action_result.status.goal_id.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.action_result.status.status
      buff.write(_get_struct_B().pack(_x))
      _x = self.action_result.status.text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.action_result.result.header.seq, _x.action_result.result.header.stamp.secs, _x.action_result.result.header.stamp.nsecs))
      _x = self.action_result.result.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_5B3f3I().pack(_x.action_result.result.is_ready, _x.action_result.result.is_reset, _x.action_result.result.is_moving, _x.action_result.result.obj_detected, _x.action_result.result.fault_status, _x.action_result.result.position, _x.action_result.result.requested_position, _x.action_result.result.current, _x.action_feedback.header.seq, _x.action_feedback.header.stamp.secs, _x.action_feedback.header.stamp.nsecs))
      _x = self.action_feedback.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.action_feedback.status.goal_id.stamp.secs, _x.action_feedback.status.goal_id.stamp.nsecs))
      _x = self.action_feedback.status.goal_id.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.action_feedback.status.status
      buff.write(_get_struct_B().pack(_x))
      _x = self.action_feedback.status.text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.action_feedback.feedback.header.seq, _x.action_feedback.feedback.header.stamp.secs, _x.action_feedback.feedback.header.stamp.nsecs))
      _x = self.action_feedback.feedback.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_5B3f().pack(_x.action_feedback.feedback.is_ready, _x.action_feedback.feedback.is_reset, _x.action_feedback.feedback.is_moving, _x.action_feedback.feedback.obj_detected, _x.action_feedback.feedback.fault_status, _x.action_feedback.feedback.position, _x.action_feedback.feedback.requested_position, _x.action_feedback.feedback.current))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.action_goal is None:
        self.action_goal = robotiq_2f_gripper_msgs.msg.CommandRobotiqGripperActionGoal()
      if self.action_result is None:
        self.action_result = robotiq_2f_gripper_msgs.msg.CommandRobotiqGripperActionResult()
      if self.action_feedback is None:
        self.action_feedback = robotiq_2f_gripper_msgs.msg.CommandRobotiqGripperActionFeedback()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.action_goal.header.seq, _x.action_goal.header.stamp.secs, _x.action_goal.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_goal.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_goal.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.action_goal.goal_id.stamp.secs, _x.action_goal.goal_id.stamp.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_goal.goal_id.id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_goal.goal_id.id = str[start:end]
      _x = self
      start = end
      end += 30
      (_x.action_goal.goal.emergency_release, _x.action_goal.goal.emergency_release_dir, _x.action_goal.goal.stop, _x.action_goal.goal.position, _x.action_goal.goal.speed, _x.action_goal.goal.force, _x.action_result.header.seq, _x.action_result.header.stamp.secs, _x.action_result.header.stamp.nsecs,) = _get_struct_BIB3f3I().unpack(str[start:end])
      self.action_goal.goal.emergency_release = bool(self.action_goal.goal.emergency_release)
      self.action_goal.goal.stop = bool(self.action_goal.goal.stop)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_result.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_result.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.action_result.status.goal_id.stamp.secs, _x.action_result.status.goal_id.stamp.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_result.status.goal_id.id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_result.status.goal_id.id = str[start:end]
      start = end
      end += 1
      (self.action_result.status.status,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_result.status.text = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_result.status.text = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.action_result.result.header.seq, _x.action_result.result.header.stamp.secs, _x.action_result.result.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_result.result.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_result.result.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 29
      (_x.action_result.result.is_ready, _x.action_result.result.is_reset, _x.action_result.result.is_moving, _x.action_result.result.obj_detected, _x.action_result.result.fault_status, _x.action_result.result.position, _x.action_result.result.requested_position, _x.action_result.result.current, _x.action_feedback.header.seq, _x.action_feedback.header.stamp.secs, _x.action_feedback.header.stamp.nsecs,) = _get_struct_5B3f3I().unpack(str[start:end])
      self.action_result.result.is_ready = bool(self.action_result.result.is_ready)
      self.action_result.result.is_reset = bool(self.action_result.result.is_reset)
      self.action_result.result.is_moving = bool(self.action_result.result.is_moving)
      self.action_result.result.obj_detected = bool(self.action_result.result.obj_detected)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_feedback.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_feedback.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.action_feedback.status.goal_id.stamp.secs, _x.action_feedback.status.goal_id.stamp.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_feedback.status.goal_id.id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_feedback.status.goal_id.id = str[start:end]
      start = end
      end += 1
      (self.action_feedback.status.status,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_feedback.status.text = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_feedback.status.text = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.action_feedback.feedback.header.seq, _x.action_feedback.feedback.header.stamp.secs, _x.action_feedback.feedback.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_feedback.feedback.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_feedback.feedback.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 17
      (_x.action_feedback.feedback.is_ready, _x.action_feedback.feedback.is_reset, _x.action_feedback.feedback.is_moving, _x.action_feedback.feedback.obj_detected, _x.action_feedback.feedback.fault_status, _x.action_feedback.feedback.position, _x.action_feedback.feedback.requested_position, _x.action_feedback.feedback.current,) = _get_struct_5B3f().unpack(str[start:end])
      self.action_feedback.feedback.is_ready = bool(self.action_feedback.feedback.is_ready)
      self.action_feedback.feedback.is_reset = bool(self.action_feedback.feedback.is_reset)
      self.action_feedback.feedback.is_moving = bool(self.action_feedback.feedback.is_moving)
      self.action_feedback.feedback.obj_detected = bool(self.action_feedback.feedback.obj_detected)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_5B3f = None
def _get_struct_5B3f():
    global _struct_5B3f
    if _struct_5B3f is None:
        _struct_5B3f = struct.Struct("<5B3f")
    return _struct_5B3f
_struct_5B3f3I = None
def _get_struct_5B3f3I():
    global _struct_5B3f3I
    if _struct_5B3f3I is None:
        _struct_5B3f3I = struct.Struct("<5B3f3I")
    return _struct_5B3f3I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_BIB3f3I = None
def _get_struct_BIB3f3I():
    global _struct_BIB3f3I
    if _struct_BIB3f3I is None:
        _struct_BIB3f3I = struct.Struct("<BIB3f3I")
    return _struct_BIB3f3I
