<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mywristcamera" >
  <xacro:property name="wrist_radius" value="0.04" />
  <xacro:property name="wrist_length" value="0.02" />

  <xacro:macro name="mywristcamera" params="parent *origin">
    
    <link name="wrist_attach">
      <visual>
        <origin xyz="${wrist_length/2} 0 0.0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <cylinder radius="${wrist_radius}" length="${wrist_length}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="${wrist_length/2} 0 0.0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <cylinder radius="${wrist_radius}" length="${wrist_length}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="${wrist_length/2} 0 0" rpy="0 ${pi/2} 0"/>
        <mass value="0.01" />
        <inertia  ixx="1.0" ixy="0.0"  ixz="0.0"  iyy="100.0"  iyz="0.0"  izz="1.0" />
      </inertial>
    </link>

    <gazebo reference="wrist_attach">
      <material>Gazebo/FlatBlack</material>
    </gazebo>

    <joint name="wrist_joint" type="fixed">
        <parent link="${parent}"/>
        <child link="wrist_attach"/>
        <xacro:insert_block name="origin"/>
    </joint>

    <xacro:property name="camera_link" value="0.02" /> <!-- Size of square 'camera' box -->
    <joint name="camera_joint" type="fixed">
      <origin xyz="${wrist_length/2} 0 ${wrist_radius+camera_link/2}" rpy="0 0 0"/>
      <parent link="wrist_attach"/>
      <child link="camera_link"/>
    </joint>

    <!-- Camera -->
    <link name="camera_link">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${camera_link} ${camera_link} ${camera_link}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${camera_link} ${camera_link} ${camera_link}"/>
        </geometry>
        <!-- <material name="red"/> -->
      </visual>

      <inertial>
        <mass value="1e-5" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
      </inertial>
    </link>

    <!-- camera -->
    <gazebo reference="camera_link">
      <material>Gazebo/RedTransparent</material>
      <sensor type="camera" name="wrist_camera">
        <update_rate>20.0</update_rate>
        <camera name="wrist_cam">
          <horizontal_fov>0.69</horizontal_fov>
          <image>
            <width>640</width>
            <height>480</height>
            <format>R8G8B8</format>
          </image>
          <clip>
            <near>0.01</near>
            <far>10</far>
          </clip>
          <noise>
            <type>gaussian</type>
            <!-- Noise is sampled independently per pixel on each frame.
                That pixel's noise value is added to each of its color
                channels, which at that point lie in the range [0,1]. -->
            <mean>0.0</mean>
            <stddev>0.007</stddev>
          </noise>
        </camera>
        <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>0.0</updateRate>
          <cameraName>myur5e/wrist_camera</cameraName>
          <imageTopicName>wrist_image_raw</imageTopicName>
          <cameraInfoTopicName>wrist_camera_info</cameraInfoTopicName>
          <frameName>camera_link</frameName>
          <hackBaseline>0.07</hackBaseline>
          <distortionK1>0.0</distortionK1>
          <distortionK2>0.0</distortionK2>
          <distortionK3>0.0</distortionK3>
          <distortionT1>0.0</distortionT1>
          <distortionT2>0.0</distortionT2>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>

</robot>
