# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robotiq_msgs/CModelCommandFeedback.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CModelCommandFeedback(genpy.Message):
  _md5sum = "0c22872a7859572c1fc9fe8ee6018789"
  _type = "robotiq_msgs/CModelCommandFeedback"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# Feedback
float64     position
bool        activated
bool        stalled
bool        reached_goal

"""
  __slots__ = ['position','activated','stalled','reached_goal']
  _slot_types = ['float64','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       position,activated,stalled,reached_goal

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CModelCommandFeedback, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.position is None:
        self.position = 0.
      if self.activated is None:
        self.activated = False
      if self.stalled is None:
        self.stalled = False
      if self.reached_goal is None:
        self.reached_goal = False
    else:
      self.position = 0.
      self.activated = False
      self.stalled = False
      self.reached_goal = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_d3B().pack(_x.position, _x.activated, _x.stalled, _x.reached_goal))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 11
      (_x.position, _x.activated, _x.stalled, _x.reached_goal,) = _get_struct_d3B().unpack(str[start:end])
      self.activated = bool(self.activated)
      self.stalled = bool(self.stalled)
      self.reached_goal = bool(self.reached_goal)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_d3B().pack(_x.position, _x.activated, _x.stalled, _x.reached_goal))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 11
      (_x.position, _x.activated, _x.stalled, _x.reached_goal,) = _get_struct_d3B().unpack(str[start:end])
      self.activated = bool(self.activated)
      self.stalled = bool(self.stalled)
      self.reached_goal = bool(self.reached_goal)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_d3B = None
def _get_struct_d3B():
    global _struct_d3B
    if _struct_d3B is None:
        _struct_d3B = struct.Struct("<d3B")
    return _struct_d3B
