(cl:defpackage robotiq_msgs-msg
  (:use )
  (:export
   "<CMODELCOMMAND>"
   "CMODELCOMMAND"
   "<CMODELCOMMANDACTION>"
   "CMODELCOMMANDACTION"
   "<CMODELCOMMANDACTIONFEEDBACK>"
   "CMODELCOMMANDACTIONFEEDBACK"
   "<CMODELCOMMANDACTIONGOAL>"
   "CMODELCOMMANDACTIONGOAL"
   "<CMODELCOMMANDACTIONRESULT>"
   "CMODELCOMMANDACTIONRESULT"
   "<CMODELCOMMANDFEEDBACK>"
   "CMODELCOMMANDFEEDBACK"
   "<CMODELCOMMANDGOAL>"
   "CMODELCOMMANDGOAL"
   "<CMODELCOMMANDRESULT>"
   "CMODELCOMMANDRESULT"
   "<CMODELSTATUS>"
   "CMODELSTATUS"
  ))

