; Auto-generated. Do not edit!


(cl:in-package robotiq_2f_gripper_msgs-msg)


;//! \htmlinclude CommandRobotiqGripperActionGoal.msg.html

(cl:defclass <CommandRobotiqGripperActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type robotiq_2f_gripper_msgs-msg:CommandRobotiqGripperGoal
    :initform (cl:make-instance 'robotiq_2f_gripper_msgs-msg:CommandRobotiqGripperGoal)))
)

(cl:defclass CommandRobotiqGripperActionGoal (<CommandRobotiqGripperActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CommandRobotiqGripperActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CommandRobotiqGripperActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robotiq_2f_gripper_msgs-msg:<CommandRobotiqGripperActionGoal> is deprecated: use robotiq_2f_gripper_msgs-msg:CommandRobotiqGripperActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <CommandRobotiqGripperActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robotiq_2f_gripper_msgs-msg:header-val is deprecated.  Use robotiq_2f_gripper_msgs-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <CommandRobotiqGripperActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robotiq_2f_gripper_msgs-msg:goal_id-val is deprecated.  Use robotiq_2f_gripper_msgs-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <CommandRobotiqGripperActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robotiq_2f_gripper_msgs-msg:goal-val is deprecated.  Use robotiq_2f_gripper_msgs-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CommandRobotiqGripperActionGoal>) ostream)
  "Serializes a message object of type '<CommandRobotiqGripperActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CommandRobotiqGripperActionGoal>) istream)
  "Deserializes a message object of type '<CommandRobotiqGripperActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CommandRobotiqGripperActionGoal>)))
  "Returns string type for a message object of type '<CommandRobotiqGripperActionGoal>"
  "robotiq_2f_gripper_msgs/CommandRobotiqGripperActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CommandRobotiqGripperActionGoal)))
  "Returns string type for a message object of type 'CommandRobotiqGripperActionGoal"
  "robotiq_2f_gripper_msgs/CommandRobotiqGripperActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CommandRobotiqGripperActionGoal>)))
  "Returns md5sum for a message object of type '<CommandRobotiqGripperActionGoal>"
  "f0063c16461ada508b5134444e0915f7")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CommandRobotiqGripperActionGoal)))
  "Returns md5sum for a message object of type 'CommandRobotiqGripperActionGoal"
  "f0063c16461ada508b5134444e0915f7")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CommandRobotiqGripperActionGoal>)))
  "Returns full string definition for message of type '<CommandRobotiqGripperActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%CommandRobotiqGripperGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: robotiq_2f_gripper_msgs/CommandRobotiqGripperGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# See Robotiq documentation for fields documentation.~%# See Robotiq documentation for fields documentation.~%~%#goal definition~%bool emergency_release~%uint32 emergency_release_dir~%bool stop~%float32 position #[m] Distance in bewteen fingers ~%float32 speed    #[m/s] Speed (Min: 0.013m/s - Max: 0.1m/s)~%float32 force    #[%] Percentage of gripper force to apply (Min: 0.0% - Max: 100.0%)~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CommandRobotiqGripperActionGoal)))
  "Returns full string definition for message of type 'CommandRobotiqGripperActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%CommandRobotiqGripperGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: robotiq_2f_gripper_msgs/CommandRobotiqGripperGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# See Robotiq documentation for fields documentation.~%# See Robotiq documentation for fields documentation.~%~%#goal definition~%bool emergency_release~%uint32 emergency_release_dir~%bool stop~%float32 position #[m] Distance in bewteen fingers ~%float32 speed    #[m/s] Speed (Min: 0.013m/s - Max: 0.1m/s)~%float32 force    #[%] Percentage of gripper force to apply (Min: 0.0% - Max: 100.0%)~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CommandRobotiqGripperActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CommandRobotiqGripperActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'CommandRobotiqGripperActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
